name: create release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: zip files
        run: |
          zip -r release.zip . -x ".github/*"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true